### ISSUE TITLE
Properties panel ? 

### ISSUE THREAD

**Issue by Diaskhan** [evanyangg/vue-bpmn-modeler#2]
Do u have some ideas ? How to implement properties panel ? 
 There must be some events, like select?

Or maybe copy paste elements ?

**Comment by evanyangg** [comment]
Sorry, I was a bit busy before。
I am going to update this repo in the 2nd week of Oct.
(include properties panel ...)
and about properties panel:
https://github.com/bpmn-io/bpmn-js-properties-panel
https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension
