### ISSUE TITLE
BpmnViewer 在自己的项目怎么使用呢

### ISSUE THREAD

**Issue by tony2y** [evanyangg/vue-bpmn-modeler#7]
![image](https://user-images.githubusercontent.com/38598582/112929550-3c967480-914b-11eb-9a1d-ee35adefdbdd.png)
这样引入？

**Comment by evanyangg** [comment]
@tony2y readme 里面有说明
```javascript
import VueBpmnModeler from "vue-bpmn-modeler";
Vue.use(VueBpmnModeler);
```
这种方式
