### ISSUE TITLE
项目中引入这个BpmnViewer，没有任何效果

### ISSUE THREAD

**Issue by tony2y** [evanyangg/vue-bpmn-modeler#8]
![image](https://user-images.githubusercontent.com/38598582/115424316-2f901100-a231-11eb-8cf1-5c5d3d5e219c.png)
![image](https://user-images.githubusercontent.com/38598582/115424473-52bac080-a231-11eb-8f6a-4a4c3d5a72af.png)

**Comment by tony2y** [comment]
想实现这个颜色显示，需要怎么处理呢。

**Comment by tony2y** [comment]
![image](https://user-images.githubusercontent.com/38598582/115424616-72ea7f80-a231-11eb-8732-6e23d21fadb1.png)

**Comment by evanyangg** [comment]
箭头线的颜色显示吗
